### ISSUE TITLE
Surf get and post requests do not work

### ISSUE THREAD

**Issue by Kerollmops** [rustasync/surf#72]
When I tried surf for make get request on `https://static.crates.io/crates/{crate}/{crate}-{version}.crate` for example I get CloudFront responding 501 Not Yet Implemented, "The request could not be satisfied". Cloudfront is not the only website that do not like surf's get requests.

I also tried to make surf post requests, those only worked with the `curl-client` as the `hyper-client` do not send the body to the server. There is already an open issue about this #46.

So I end up doing crazy things that worked.
I declared two dependencies of the same package and use the one with curl for the post and the one with hyper for the get requests.

```toml
[dependencies.surf]
git = "https://github.com/badboy/surf.git"
branch = "hyper-client"
default-features = false
features = ["hyper-client"]

[dependencies.surf-curl]
package = "surf"
git = "https://github.com/rustasync/surf.git"
branch = "master"
```
